name: sliderflow
description: "It's a futuristic slider widget."
version: 1.0.1
homepage: https://github.com/thehelmsdeep/sliderflow

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
